version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env-non-dev
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    container_name: db_app
    command:
      -p 1221
    expose:
      - 1221
    env_file:
      - .env-non-dev
